const clothes = [
    {
        name: "Sponge bob cleats",
        price: 119.99,
        inStock: true,
        brand: "Sponge bob",
        img: "https://phenomelitebrand.com/cdn/shop/files/SpongebobProductShot4_535x.png?v=1740765484",
        alt: "Yellow cleats with Sponge bob",
    },
        {
        name: "Ukrainian Jersey",
        price: 34.99,
        inStock: true,
        brand: "Adidas",
        img: "img/116401-removebg-preview.png",
        alt: "Yellow and blue soccer jersey",
    },    
           {
        name: "2022 World Cup Soccer Ball",
        price: 39.99,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    },        {
        name: "",
        price: ,
        inStock: true,
        brand: "",
        img: "",
        alt: "",
    }, 
]